### ISSUE TITLE
Create TO-DO list

### ISSUE THREAD

**Issue by kev-the-dev** [uf-mil/mil_common#2]
We should create a list of things to add / migrate to software-common

**Comment by sentree** [comment]
We can either make a wiki page or use this issue to track the packages that need to be migrated. Any preference?

**Comment by kev-the-dev** [comment]
Vision Lib: add any generic vision library functions from navigator + subjugator to the mil_vision_lib package

@DSsoto

**Comment by kev-the-dev** [comment]
Drivers: Looks like there are some drivers / hardware interfaces that might be better off in the common repo. I see the roboteq motor controller drivers, xbox controller driver, and hydrophone / paulboard stuff as good candidates

**Comment by kev-the-dev** [comment]
GNC: some gnc related things could be useful in generic versions, such as the OgridArbiter, MRAC (if we move all robot specific parameters to ros params), certain components of the selfcheckers in sub and navigator. @mattlangford

**Comment by mattlangford** [comment]
I think the ogrid arbiter would be good to move (I can do that). MRAC is pretty specific to a boat (things were tuned to navigator), so I don't think that needs to be moved.
The self checks have to be tuned to each platform, I tried to make them general for navigator but there are a lot of things that need to be checked in special ways that aren't general enough - so I think it should stay.
Roboteq wasn't even our package, so no move. The Xbox controller driver wasn't ours, and the controller node was pretty specific to navigator, so I think it should stay.
Paulboard hydrophone stuff - for sure move, I bet @dsoto would be willing to do rhat

**Comment by sentree** [comment]
This can be closed since #5 is being used to track the progress now.
