### ISSUE TITLE
GREAT MERGE: Migrate uf_common non-msg stuff to mil_tools

### ISSUE THREAD

**Issue by kev-the-dev** [uf-mil/mil_common#24]
Move the c++ library in uf_common (now mil_msgs) and any scripts to mil_tools.

I'm working on this.

**Comment by DSsoto** [comment]
In what packages will you be replacing the current references to uf_common?
Also look at #25.

Our goal should be to click [here](https://github.com/search?utf8=%E2%9C%93&q=org%3Auf-mil+uf_common&type=Code) and get no results.

**Comment by DSsoto** [comment]
This was done in #28.
