### ISSUE TITLE
Develop LabelMe ros interface / tools

### ISSUE THREAD

**Issue by kev-the-dev** [uf-mil/mil_common#31]
As discussed in the last two meetings, we are developing a branch of LabelMe to label logged data with object polygons for testing and training. We discussed producing bag files from these labels, containing images and the labeling data. We also discussed having a python class which will play these special bags and, provided with a verification predicate, assess the efficacy of a vision algorithm. I will be PRing the message files we agreed for storing this data. 

@tessbianchi can you write the tooling needed to produce these bag files from the labeling data? Note: the bag should contain all the images of the original bag, not just the labeled images.

**Comment by kev-the-dev** [comment]
For reference, here is the design of the ROS/LabelMe testing system we developed at tonights meeting.

![design](http://i.imgur.com/17fVVdv.jpg)

@aaron-iglesias has agreed to implement it. It should use the messages added in #32

**Comment by sentree** [comment]
I am assuming validation is done client-side with bags pulled from the [unit test server](https://ci.mil.ufl.edu/unit_test_data). If that is the case, then we can do some automated packaging. This is the system I had in mind for managing that (so long as @tessbianchi wants to handle the LabelMe side of it, I'm not touching that):

* The LabelMe web application will have read only access to the bags directory
* Users will be able to select a bag they want to add to the segmentation pool
* The bag will be sliced up by a ROS node at an interval to get the GT images for segmentation
* People segment the images
* Upon completion of all of the images in a bag, the LabelMe web application triggers a ROS node to auto-magically reassemble the bag and drop it into the [unit test server](https://ci.mil.ufl.edu/unit_test_data) directory specified when the user selected the bag for segmentation
* Some kind of notification process

The only issue I can see here is that the web application should obviously not be importing ROS packages to handle bags directly. This means we would need to get it and the ROS nodes handling the bags to talk in some other way.

**Comment by kev-the-dev** [comment]
@aaron-iglesias you can use this issue for discussion of this

Some links to point in the right direciton:

* [The rosbag library](http://wiki.ros.org/rosbag/Cookbook) for programmaticly reading, writing bag files

* [rostest](http://wiki.ros.org/rostest/Writing) for writing tests that work with the ros build/test system and can be used by our CI

* [The pathmarker unittest](https://github.com/uf-mil/SubjuGator/tree/master/perception/sub8_perception/test) I wrote recently which similar to what we want to but just has hardcoded ground truth instead of through the LabelMe interface

**Comment by kev-the-dev** [comment]
Some more notes

We want the pipeline for this to work as follows:
1. We call a script/ email a tess with the following inputs
    1. A bag containing some imaging sonar / camera data to be labeled ex: ```transdec1.bag```
    1. An image topic to extract labeling images from, ex: ```/camera/front/left/image_rect_color```
    1. A list of time ranges within the bag to extract labeling images from ex: ```[ [2.0, 3.0], [7.0, 15.3 ]]```
    1. A list of names for the future labeled bags for each time range ex:```["buoy1", "buoy2"]```
    1. A list of sampling frequencies, corresponding to each time range given. This represents how many images per second should be extracted in this range for labeling ex:: ```[10, 15]```
1. Sampling images are extracted from the specified bag using the specified parameters and put on the LabelMe site under the correct bag name.
1. Once all sample images for this bag are labeled, new bag(s) are produced:
    1. Each bag contains one time interval for this bag, named the name specific in Step 1 or ```buoy1.bag, buoy2.bag```
    1. Contains all original data from this time interval (images and everything else)
    1. Also contains a new topic at LABELED_IMAGE_TOPIC/labels, ex: ```/camera/front/left/image_rect_color/labels```
    1. At times nearby the corresponding sample images, messages are at this topic containing```mil_msgs/LabeledObjects``` messages
    1. The header of these messages has an IDENTICAL stamp to the corresponding frame and the frame_id of the camera
    1. The objects in these messages contain the labeled polygons and meta data from LabelMe for this frame
1. Labeled bags are automatically put in the CI folder on the file server, so they can used in catkin_download_test_data for perception unit tests

**Comment by kev-the-dev** [comment]
https://github.com/ironmig/mil_common/blob/labelme/utils/mil_tools/nodes/label_me_bag.py

Been working on the bag / labelme interface script today. Almost done. Given a yaml like this:
```
bags:
  - file: orange_pipes.bag
    labeled_file: orange_pipes_labeled.bag
    segments:
      - name: path_marker_pool_1
        start: 1.0
        stop: 10.0
        topic: /down/left/image_raw
        frame: down_cam
        freq: 0.5
      - name: path_marker_pool_2
        start: 15.0
        stop: 20.0
        topic: /down/left/image_raw
        frame: down_cam
        freq: 1.0

```
I can go through the listed bags and put segmented images in the correct directory for LabelMe to display them on the web interface. Given the same config, I can also go through the LabelMe annotations and match up bag frames to LabelMe annotation XML files. Only think left is parsing the XML files into the ros message.

**Comment by kev-the-dev** [comment]
Good stuff going on in #44

**Comment by sentree** [comment]
With #44 merged, we are getting ever close to a system that converts dollars to AUVSI competition victories. When I get back to the lab, I want to sit down and look over what will be required to get this and our fork of LabelMe up and running on the server.

**Comment by kev-the-dev** [comment]
We decided on labelbox.io instead, and have interfaces written
