### ISSUE TITLE
ONLINE BAGGER: integrate with the bag utility

### ISSUE THREAD

**Issue by kev-the-dev** [uf-mil/mil_common#46]
To make the online bagger more useful on test days, it should integrate with the bag command we made in two ways:
1. Online bagger should read the same environment variables the bag utility does to decide which topics to buffer. Perhaps instead of adding all of the bagging topics, it would add all the topics in a certain reserved variable, like ```bag_online```, so the bag utility configuration can specify which to bag ex: ```bag_online="$bag_frontcam $bag_gnc"```
1. Add an option to the online bagger service to dump a list of topics (space separated). This will allow the bag utility to add a new flag for dumping the past n seconds with the specified topics.

**Comment by kev-the-dev** [comment]
I started working on the changes to online bagger for 1

**Comment by sentree** [comment]
Thanks @ironmig,

First off, the utility is just called `bag`.

What would the purpose of the `bag_online` variable be? We want it to be very intuitive. If a user types `bag gnc -o 60`, they should get the expected result, not a message telling them the GNC topics are not supported.

We also need online_bagger to respect the `BAG_ALWAYS` and `BAG_DIR` environment variables as well as place the bags in the correct dated folders.

I also have an idea as to how to actually get RAM limiting to work, so stay tuned on that.

**Comment by kev-the-dev** [comment]
I could implement it that way, but I think it would be better to specify which topics you want to buffer, because buffering everything listed in the aliases may be way too big. Each camera topic alone is 1.6 gigabytes a minute, which will all be in RAM.

With all three camera topics plus blueview thats 6.4 gigabytes of RAM for a 60 second buffer, assuming python manages it as efficiently as possible. 

To make it remain intuituve, you could type ```-b``` before the topics, than only topics within ```BAG_ONLINE``` will autocomplete.

**Comment by sentree** [comment]
Have you run the numbers for the other topics we have in the bagging variables? I think cameras would be much larger than the rest and even still, we only use about 2 GB of the 32 GB we have available to us in RAM. I think it would be worthwhile to keep everything accessible.

**Comment by kev-the-dev** [comment]
Alright I'll implement it using all bag aliases and we'll do a testing to see if it's a problem on SubjuGator.

**Comment by ghost** [comment]
Is this RAM hogging something that we will have to watch out for on NaviGator and/or future MIL ROSbots?

**Comment by sentree** [comment]
Hopefully, we will be able to get identical compute on both SubjuGator and NaviGator. This will help with compatibility issues, and the hardware on SubjuGator right now is more than enough for our needs. The majority of our software is very light on RAM and this program can be tuned to the amount available, so I don't see many problems with it.

**Comment by sentree** [comment]
This is mostly complete. The online bagger utility is working in a stable way, a bag is generated for each vehicle kill, and the bag command is able to create bags both forward and backward in time.

For future reference (or if anyone would like to attempt this now), the idea that I had for RAM limiting was keeping track of the RAM used, waiting for it to get to the limit, then setting a limit for the number of messages that should be stored for each topic. This would work under the assumption that Python will stop accumulating new RAM for messages once older messages are removed. In other words, the new messages will take the place of the old ones in physical memory space.

If that assumption is correct, this should only take a few solid days to get working; however, the time based limiting works for our needs and there are more important tasks to work on before the RoboSub competition.
