### ISSUE TITLE
File migration list (sweet, sweet, great, great merge)

### ISSUE THREAD

**Issue by kev-the-dev** [uf-mil/mil_common#5]
Please list all files you want migrated from sub8 or navigator to the software-common repo. List the full path of where the file is from, and where it should go in the new repo. If the file is going to be a merge of sub8 and navigator files, say so. 

For now we are just worrying about getting the files in the repo. We will go through and refactor later, but feel free to leave notes on what needs to be done.

**Comment by kev-the-dev** [comment]
# TOOLS

**sub8**
utils/sub8_ros_tools/sub8_misc_tools/text_effects.py
utils/sub8_ros_tools/sub8_ros_tools/geometry_helpers.py
utils/sub8_ros_tools/sub8_ros_tools/image_helpers
utils/sub8_ros_tools/sub8_ros_tools/init_helpers.py
utils/sub8_ros_tools/sub8_ros_tools/msg_helpers.py
utils/sub8_ros_tools/sub8_ros_tools/threading_helpers.py
utils/sub8_ros_tools/sub8_ros_tools/__init__.py
utils/sub8_ros_tools/setup.py
utils/sub8_ros_tools/package.xml 


**navigator**
utils/navigator_tools/nodes/clicked_point_recorder.py
utils/navigator_tools/nodes/tf_fudger.py
utils/navigator_tools/nodes/video_player
utils/navigator_tools/nodes/ogrid_draw.py
utils/navigator_tools/nodes/tf_to_gazebo.py
utils/navigator_tools/nodes/navigator_tools/cv_debug.py
utils/navigator_tools/nodes/navigator_tools/geometry_helpers.py

***new sub8***
utils/sub8_ros_tools/CMakeLists.txt
utils/sub8_ros_tools/sub8_ros_tools/func_helpers.py
utils/sub8_ros_tools/sub8_misc_tools/download.py
utils/sub8_ros_tools/test_ros_tools/test_ros_tools.py
utils/sub8_misc_tools/__init__.py
utils/sub8_ros_tools/sub8_tools/__init__.py

***new navigator***
utils/navigator_tools/navigator_tools/cv_debug.py
utils/navigator_tools/navigator_tools/rviz_helpers.py
utils/navigator_tools/navigator_tools/geometry_helpers.py
utils/navigator_tools/navigator_tools/msg_helpers.py
utils/navigator_tools/set.py
utils/navigator_tools/navigator_tools/__init__.py
utils/navigator_tools/package.xml
utils/navigator_tools/CMakeLists.txt



I already did all of this in #1, so just checkout mil_dev_tools to that branch when history is in order to apply all needed re factoring.

**Comment by kev-the-dev** [comment]
# GNC

- I think we should make a mil_gnc package, for gnc stuff

**navigator**
gnc/navigator_msg_multiplexer/nodes/ogrid_arbiter.py -> mil_gnc/mil_gnc/

**sub8**
legacy/c3_trajectory_generator/src/ -> mil_gnc/src/c3_trajectory_generator
legacy/c3_trajectory_generator/include/ -> mil_gnc/include/c3_trajectory_generator

**Comment by kev-the-dev** [comment]
# Hydrophones

- Create mil_hardware package

**sub8**
drivers/hydrophones -> mil_hardware/
driers/paulboard_driver -> mil_hardware/

**Comment by kev-the-dev** [comment]
@DSsoto Add whatever generic perception files from sub8 and navigator should be moved over. We'll have a chance to refactor / merge them after moving

**Comment by kev-the-dev** [comment]
@whispercoros I'm done with my files. After David is done you can do the git stuff.

**Comment by mattlangford** [comment]
I think GNC may be too vehicle specific to have a general package right now. Trajectory generation is pretty specific to the platform, the occupancy grid multiplexer doesn't really make sense to need to use for the sub. Control nodes like thruster mappers and such are very tied into the platform.
Most of these things could be generalized to any vehicle but since they aren't currently, they should live on their own.

**Comment by kev-the-dev** [comment]
tru

**Comment by DSsoto** [comment]
# drivers
## SubjuGator -> mil_common
drivers/sub8_sonar -> mil_common/drivers/mil_sonar
drivers/paulboard_driver -> drivers/paulboard_driver

# perception
## NaviGator - mil_common
perception/navigator_vision/include/navigator_vision_lib -> perception/mil_viision/include/mil_vision_lib
perception/navigator_vision/src/navigator_vision_lib -> perception/mil_viision/src/mil_vision_lib
perception/navigator_vision/object_classification -> perception/mil_viision/scripts/object_classification
perception/navigator_vision/ros_tools -> perception/mil_viision/scripts/ros_tools

## sub

perception/sub8_perception/ros_tools -> perception/mil_viision/scripts/ros_tools

**Comment by sentree** [comment]
Everyone involved here should have a look at #8 for the next steps.

**Comment by kev-the-dev** [comment]
I added all the missing files I could think of. It might be easier to just move the entire utils/navigator_tools and utils/sub8_ros_tools folders and we can remove files we wont keep

**Comment by sentree** [comment]
I can move the full folders, but we need to be sure of the full set of what you would like to be moved before too much work is placed on top of the merge. I guess for the sake of keeping things in-tact, we should only be moving full packages here. Does anyone have any objections or additions to just moving the full packages that each of the above files and folders is a part of? Also, is rolling back and redoing the merge an agreed upon idea?

**Comment by mattlangford** [comment]
I have tools covered, no need to do it there. Might be good for other packages though.

**Comment by mattlangford** [comment]
I'll add the missing navigator files. There were some changes I wanted to make on how the tools were set up which I why I say let me handle it.

**Comment by sentree** [comment]
Update: A vote in the lab was unanimously in favor of moving complete packages.

**Comment by DSsoto** [comment]
These files were moved over in #11. Closing.
