### ISSUE TITLE
Make online bagger an action server (hear me out)

### ISSUE THREAD

**Issue by kev-the-dev** [uf-mil/mil_common#69]
I think it would be more appropriate for the triggering of bag writes from online bagger to be through the ROS action API than the ROS service API. 

Why?
* writing large (many gigabyte) bags to disk can take several seconds, which will cause clients (such as alarm callbacks, missions, etc) to freeze for this time
* actions allow a feedback, which will notify the user from the client side which topics are buffered, how many messages, etc instead of having to look through online bagger logs
* actions have built in preempt functionality, so new bag actions can be canceled or superseed current ones
* would make future functionality, like storing new messages even as a bug takes place easier to implement

**Comment by kingkevlar** [comment]
You have been heard
